export const PermissionCode = {
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_LIVE: 'dashboard.live',
  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_MANAGE: 'employees.manage',
  DEPARTMENTS_MANAGE: 'departments.manage',
  ATTENDANCE_VIEW_ALL: 'attendance.view_all',
  ATTENDANCE_VIEW_TEAM: 'attendance.view_team',
  ATTENDANCE_VIEW_SELF: 'attendance.view_self',
  ACCESS_OPERATE: 'access.operate',
  ACCESS_VIEW_EVENTS: 'access.view_events',
  PPE_POLICY_MANAGE: 'ppe.policy.manage',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  NOTIFICATIONS_VIEW: 'notifications.view',
  SETTINGS_MANAGE: 'settings.manage',
  USERS_MANAGE: 'users.manage',
  AUDIT_VIEW: 'audit.view',
  PROFILE_VIEW_SELF: 'profile.view_self',
  PROFILE_EDIT_SELF: 'profile.edit_self',
} as const;

export type PermissionCode = (typeof PermissionCode)[keyof typeof PermissionCode];

/** Role → permission codes (source of truth for seed + UI hints). */
export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  ADMIN: Object.values(PermissionCode),
  GUARD: [
    PermissionCode.DASHBOARD_VIEW,
    PermissionCode.DASHBOARD_LIVE,
    PermissionCode.EMPLOYEES_VIEW,
    PermissionCode.ATTENDANCE_VIEW_SELF,
    PermissionCode.ACCESS_OPERATE,
    PermissionCode.ACCESS_VIEW_EVENTS,
    PermissionCode.NOTIFICATIONS_VIEW,
    PermissionCode.PROFILE_VIEW_SELF,
    PermissionCode.PROFILE_EDIT_SELF,
  ],
  SUPERVISOR: [
    PermissionCode.DASHBOARD_VIEW,
    PermissionCode.DASHBOARD_LIVE,
    PermissionCode.EMPLOYEES_VIEW,
    PermissionCode.ATTENDANCE_VIEW_ALL,
    PermissionCode.ATTENDANCE_VIEW_TEAM,
    PermissionCode.ATTENDANCE_VIEW_SELF,
    PermissionCode.ACCESS_VIEW_EVENTS,
    PermissionCode.REPORTS_VIEW,
    PermissionCode.REPORTS_EXPORT,
    PermissionCode.NOTIFICATIONS_VIEW,
    PermissionCode.PROFILE_VIEW_SELF,
    PermissionCode.PROFILE_EDIT_SELF,
  ],
  HR: [
    PermissionCode.DASHBOARD_VIEW,
    PermissionCode.EMPLOYEES_VIEW,
    PermissionCode.EMPLOYEES_MANAGE,
    PermissionCode.DEPARTMENTS_MANAGE,
    PermissionCode.ATTENDANCE_VIEW_ALL,
    PermissionCode.ATTENDANCE_VIEW_TEAM,
    PermissionCode.ATTENDANCE_VIEW_SELF,
    PermissionCode.ACCESS_VIEW_EVENTS,
    PermissionCode.REPORTS_VIEW,
    PermissionCode.REPORTS_EXPORT,
    PermissionCode.NOTIFICATIONS_VIEW,
    PermissionCode.PROFILE_VIEW_SELF,
    PermissionCode.PROFILE_EDIT_SELF,
  ],
  EMPLOYEE: [
    PermissionCode.ATTENDANCE_VIEW_SELF,
    PermissionCode.NOTIFICATIONS_VIEW,
    PermissionCode.PROFILE_VIEW_SELF,
    PermissionCode.PROFILE_EDIT_SELF,
  ],
};
